square = int(input("Введите длину стороны квадрата: "))
print()
print("Вывод:")
print("Периметр: ", square * 4)
print("Площадь: ", square ** 2)
print()
a = int(input("Введите длину прямоугольника: "))
b = int(input("Введите ширину прямоугольника: "))
print()
print("Вывод:")
print("Периметр: ", a + a + b + b)
print("Площадь: ", a * b)